global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["cstr_alertmanager:9093"]

rule_files:
  - /etc/prometheus/prometheus-rules.yml

scrape_configs:
  - job_name: submission-api
    static_configs:
      - targets: ["cstr_submission_api:8080"]
